/**
 * @author Wijdan Afifi
 */
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
public class BARANG extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BARANG.class.getName());
        DATABASE db = new DATABASE();
        
    public BARANG() {
        initComponents();
        this.setLocationRelativeTo(null);
        refreshTable();
        
        table_barang.getTableHeader().setOpaque(false);
        table_barang.getTableHeader().setBackground(new java.awt.Color(43, 57, 144));
        table_barang.getTableHeader().setForeground(java.awt.Color.BLACK);
        table_barang.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        table_barang.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sidebar_login = new javax.swing.JPanel();
        Judul = new javax.swing.JLabel();
        Label_namabrg = new javax.swing.JLabel();
        nama_barang = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        Label_kategoribrg = new javax.swing.JLabel();
        kategori_barang = new javax.swing.JComboBox<>();
        Label_jumlahbrg = new javax.swing.JLabel();
        jumlah_barang = new javax.swing.JSpinner();
        jSeparator4 = new javax.swing.JSeparator();
        tambah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        search_filter = new javax.swing.JComboBox<>();
        search_nama = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_barang = new javax.swing.JTable();
        back_dashboard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Sidebar_login.setBackground(new java.awt.Color(43, 57, 144));
        Sidebar_login.setPreferredSize(new java.awt.Dimension(300, 600));

        Judul.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Judul.setForeground(new java.awt.Color(255, 255, 255));
        Judul.setText("DATA BARANG");

        Label_namabrg.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Label_namabrg.setForeground(new java.awt.Color(255, 255, 255));
        Label_namabrg.setText("Nama Barang");

        nama_barang.setBackground(new java.awt.Color(43, 57, 144));
        nama_barang.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        nama_barang.setForeground(new java.awt.Color(255, 255, 255));
        nama_barang.setBorder(null);

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        Label_kategoribrg.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Label_kategoribrg.setForeground(new java.awt.Color(255, 255, 255));
        Label_kategoribrg.setText("Kategori Barang");

        kategori_barang.setBackground(new java.awt.Color(43, 57, 144));
        kategori_barang.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        kategori_barang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Protein", "Karbohidat" }));

        Label_jumlahbrg.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Label_jumlahbrg.setForeground(new java.awt.Color(255, 255, 255));
        Label_jumlahbrg.setText("Jumlah");

        jumlah_barang.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jumlah_barang.setValue(1);

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        tambah.setBackground(new java.awt.Color(106, 119, 198));
        tambah.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tambah.setForeground(new java.awt.Color(255, 255, 255));
        tambah.setText("TAMBAH");
        tambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tambah.setHideActionText(true);
        tambah.addActionListener(this::tambahActionPerformed);

        hapus.setBackground(new java.awt.Color(226, 35, 26));
        hapus.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        hapus.setForeground(new java.awt.Color(255, 255, 255));
        hapus.setText("HAPUS");
        hapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hapus.addActionListener(this::hapusActionPerformed);

        ubah.setBackground(new java.awt.Color(106, 119, 198));
        ubah.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ubah.setForeground(new java.awt.Color(255, 255, 255));
        ubah.setText("UBAH");
        ubah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ubah.addActionListener(this::ubahActionPerformed);

        javax.swing.GroupLayout Sidebar_loginLayout = new javax.swing.GroupLayout(Sidebar_login);
        Sidebar_login.setLayout(Sidebar_loginLayout);
        Sidebar_loginLayout.setHorizontalGroup(
            Sidebar_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sidebar_loginLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(Judul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Sidebar_loginLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(Sidebar_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Sidebar_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Label_namabrg)
                        .addComponent(jSeparator3)
                        .addComponent(nama_barang)
                        .addComponent(Label_jumlahbrg)
                        .addGroup(Sidebar_loginLayout.createSequentialGroup()
                            .addComponent(tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(67, 67, 67)
                            .addComponent(ubah))
                        .addComponent(Label_kategoribrg)
                        .addComponent(kategori_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Sidebar_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumlah_barang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)))
                    .addGroup(Sidebar_loginLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(hapus)))
                .addGap(30, 30, 30))
        );
        Sidebar_loginLayout.setVerticalGroup(
            Sidebar_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sidebar_loginLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(Judul)
                .addGap(55, 55, 55)
                .addComponent(Label_namabrg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_kategoribrg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kategori_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_jumlahbrg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jumlah_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(Sidebar_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah)
                    .addComponent(ubah))
                .addGap(28, 28, 28)
                .addComponent(hapus)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        getContentPane().add(Sidebar_login, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(175, 186, 255));

        search_filter.setForeground(new java.awt.Color(255, 255, 255));
        search_filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Protein", "Karbohidrat" }));
        search_filter.addActionListener(this::search_filterActionPerformed);

        search_nama.setText("Nama Barang");

        search.setBackground(new java.awt.Color(66, 87, 215));
        search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("CARI");
        search.addActionListener(this::searchActionPerformed);

        table_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Barang", "Nama Barang", "Kategori", "Jumlah"
            }
        ));
        table_barang.setRowHeight(25);
        jScrollPane1.setViewportView(table_barang);

        back_dashboard.setBackground(new java.awt.Color(66, 87, 215));
        back_dashboard.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        back_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        back_dashboard.setText("BACK");
        back_dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_dashboardMouseClicked(evt);
            }
        });
        back_dashboard.addActionListener(this::back_dashboardActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(back_dashboard)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(search_filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(search_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(search_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(search)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(back_dashboard)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        String nama = nama_barang.getText();
        String kategori = (String) kategori_barang.getSelectedItem();
        int jumlah = (int) jumlah_barang.getValue();

        if (!nama.isEmpty()) {

            DefaultTableModel model = (javax.swing.table.DefaultTableModel) table_barang.getModel();

            boolean update = DATABASE.tambah_barang(nama, kategori, jumlah);

            javax.swing.JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan ke Tabel!");
            model.addRow(new Object[]{nama, kategori, jumlah});

            nama_barang.setText("");
            jumlah_barang.setValue(1);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Isi Nama Barang terlebih dahulu!");
        }
    }//GEN-LAST:event_tambahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        int selectedRow = table_barang.getSelectedRow();

        if (selectedRow != 1){
            String nama = table_barang.getValueAt(selectedRow, 0).toString();

            int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah anda yakin ingin menghapus " + nama + "?",
                "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

            if(confirm == javax.swing.JOptionPane.YES_OPTION){
                boolean isDeleted = DATABASE.hapus_barang(nama);

                if (isDeleted){

                    DefaultTableModel model = (DefaultTableModel) table_barang.getModel();
                    model.removeRow(selectedRow);

                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data dari database!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris di tabel yang ingin di hapus terlebih dahulu!");
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        int selectedRow = table_barang.getSelectedRow();
        String pilihNama = table_barang.getValueAt(selectedRow, 0).toString();
        
        if(selectedRow != -1){
            String namaBaru = nama_barang.getText();
            String kategoriBaru = (String) kategori_barang.getSelectedItem();
            int jumlahBaru = (int) jumlah_barang.getValue();
            
            if(!namaBaru.isEmpty()){
                boolean isUpdated = DATABASE.ubah_barang(pilihNama, kategoriBaru, jumlahBaru, namaBaru);
                
                if(isUpdated){
                    DefaultTableModel model = (DefaultTableModel) table_barang.getModel();
                    model.setValueAt(namaBaru, selectedRow, 0);
                    model.setValueAt(kategoriBaru, selectedRow, 1);
                    model.setValueAt(jumlahBaru, selectedRow, 2);
                    
                    JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
                    
                    nama_barang.setText("");
                    jumlah_barang.setValue(1);
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal mengubah data di database!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Nama barang tidak boleh kosong");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris di tabel yang ingin diubah terlebih dahulu");
        }
    }//GEN-LAST:event_ubahActionPerformed

    private void search_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_filterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_filterActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void back_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_dashboardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_back_dashboardMouseClicked

    private void back_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_dashboardActionPerformed
        DASHBOARD board = new DASHBOARD();
        board.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_dashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BARANG().setVisible(true));
    }
    
    public void refreshTable() {
        table_barang.setModel(db.getModelBarang());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Judul;
    private javax.swing.JLabel Label_jumlahbrg;
    private javax.swing.JLabel Label_kategoribrg;
    private javax.swing.JLabel Label_namabrg;
    private javax.swing.JPanel Sidebar_login;
    private javax.swing.JButton back_dashboard;
    private javax.swing.JButton hapus;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSpinner jumlah_barang;
    private javax.swing.JComboBox<String> kategori_barang;
    private javax.swing.JTextField nama_barang;
    private javax.swing.JButton search;
    private javax.swing.JComboBox<String> search_filter;
    private javax.swing.JTextField search_nama;
    private javax.swing.JTable table_barang;
    private javax.swing.JButton tambah;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
