
import java.awt.Color;

/**
 * @author Wijdan Afifi
 */
public class DASHBOARD extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DASHBOARD.class.getName());
        BARANG brg = new BARANG();
        LOGIN login = new LOGIN();
        REGISTER reg = new REGISTER();
        LAPORAN report = new LAPORAN();
        PENGATURAN setting = new PENGATURAN();
        
    public DASHBOARD() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        pn_dashboard = new javax.swing.JPanel();
        bt_dashboard = new javax.swing.JLabel();
        pn_databarang = new javax.swing.JPanel();
        bt_databarang = new javax.swing.JLabel();
        pn_laporan = new javax.swing.JPanel();
        bt_laporan = new javax.swing.JLabel();
        pn_pengaturan = new javax.swing.JPanel();
        bt_pengaturan = new javax.swing.JLabel();
        panel_kanan = new javax.swing.JPanel();
        panel_welcome = new javax.swing.JPanel();
        border = new javax.swing.JPanel();
        main_layout = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        sidebar.setBackground(new java.awt.Color(43, 57, 144));
        sidebar.setPreferredSize(new java.awt.Dimension(200, 600));

        pn_dashboard.setBackground(new java.awt.Color(175, 186, 255));
        pn_dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_dashboardMouseExited(evt);
            }
        });

        bt_dashboard.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        bt_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        bt_dashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_dashboard.setText("DASHBOARD");
        bt_dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pn_dashboardLayout = new javax.swing.GroupLayout(pn_dashboard);
        pn_dashboard.setLayout(pn_dashboardLayout);
        pn_dashboardLayout.setHorizontalGroup(
            pn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dashboardLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(bt_dashboard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_dashboardLayout.setVerticalGroup(
            pn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_dashboardLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(bt_dashboard)
                .addGap(15, 15, 15))
        );

        pn_databarang.setBackground(new java.awt.Color(175, 186, 255));
        pn_databarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_databarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_databarangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_databarangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_databarangMouseExited(evt);
            }
        });

        bt_databarang.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        bt_databarang.setForeground(new java.awt.Color(255, 255, 255));
        bt_databarang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_databarang.setText("DATA BARANG");
        bt_databarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pn_databarangLayout = new javax.swing.GroupLayout(pn_databarang);
        pn_databarang.setLayout(pn_databarangLayout);
        pn_databarangLayout.setHorizontalGroup(
            pn_databarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_databarangLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(bt_databarang)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pn_databarangLayout.setVerticalGroup(
            pn_databarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_databarangLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(bt_databarang)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pn_laporan.setBackground(new java.awt.Color(175, 186, 255));
        pn_laporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_laporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_laporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_laporanMouseExited(evt);
            }
        });

        bt_laporan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        bt_laporan.setForeground(new java.awt.Color(255, 255, 255));
        bt_laporan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_laporan.setText("LAPORAN");
        bt_laporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pn_laporanLayout = new javax.swing.GroupLayout(pn_laporan);
        pn_laporan.setLayout(pn_laporanLayout);
        pn_laporanLayout.setHorizontalGroup(
            pn_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_laporanLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(bt_laporan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_laporanLayout.setVerticalGroup(
            pn_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_laporanLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(bt_laporan)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pn_pengaturan.setBackground(new java.awt.Color(175, 186, 255));
        pn_pengaturan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_pengaturan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_pengaturanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_pengaturanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_pengaturanMouseExited(evt);
            }
        });

        bt_pengaturan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        bt_pengaturan.setForeground(new java.awt.Color(255, 255, 255));
        bt_pengaturan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_pengaturan.setText("PENGATURAN");
        bt_pengaturan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pn_pengaturanLayout = new javax.swing.GroupLayout(pn_pengaturan);
        pn_pengaturan.setLayout(pn_pengaturanLayout);
        pn_pengaturanLayout.setHorizontalGroup(
            pn_pengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_pengaturanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_pengaturan)
                .addGap(17, 17, 17))
        );
        pn_pengaturanLayout.setVerticalGroup(
            pn_pengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_pengaturanLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(bt_pengaturan)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pn_dashboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_laporan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_databarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_pengaturan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(pn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(pn_databarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(pn_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(pn_pengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jPanel1.add(sidebar, java.awt.BorderLayout.LINE_START);

        panel_kanan.setBackground(new java.awt.Color(175, 186, 255));
        panel_kanan.setLayout(new java.awt.BorderLayout());

        panel_welcome.setBackground(new java.awt.Color(175, 186, 255));

        javax.swing.GroupLayout panel_welcomeLayout = new javax.swing.GroupLayout(panel_welcome);
        panel_welcome.setLayout(panel_welcomeLayout);
        panel_welcomeLayout.setHorizontalGroup(
            panel_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
        );
        panel_welcomeLayout.setVerticalGroup(
            panel_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panel_kanan.add(panel_welcome, java.awt.BorderLayout.PAGE_START);

        border.setBackground(new java.awt.Color(255, 255, 255));

        main_layout.setBackground(new java.awt.Color(175, 186, 255));

        javax.swing.GroupLayout main_layoutLayout = new javax.swing.GroupLayout(main_layout);
        main_layout.setLayout(main_layoutLayout);
        main_layoutLayout.setHorizontalGroup(
            main_layoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 812, Short.MAX_VALUE)
        );
        main_layoutLayout.setVerticalGroup(
            main_layoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout borderLayout = new javax.swing.GroupLayout(border);
        border.setLayout(borderLayout);
        borderLayout.setHorizontalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main_layout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        borderLayout.setVerticalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main_layout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_kanan.add(border, java.awt.BorderLayout.CENTER);

        jPanel1.add(panel_kanan, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pn_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_dashboardMouseEntered
        pn_dashboard.setBackground(new Color(66, 87, 215));        
    }//GEN-LAST:event_pn_dashboardMouseEntered

    private void pn_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_dashboardMouseExited
        pn_dashboard.setBackground(new Color(175, 186, 255));
    }//GEN-LAST:event_pn_dashboardMouseExited

    private void pn_databarangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_databarangMouseEntered
        pn_databarang.setBackground(new Color(66, 87, 215));
    }//GEN-LAST:event_pn_databarangMouseEntered

    private void pn_databarangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_databarangMouseExited
        pn_databarang.setBackground(new Color(175, 186, 255));
    }//GEN-LAST:event_pn_databarangMouseExited

    private void pn_laporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_laporanMouseEntered
        pn_laporan.setBackground(new Color(66, 87, 215));
    }//GEN-LAST:event_pn_laporanMouseEntered

    private void pn_laporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_laporanMouseExited
        pn_laporan.setBackground(new Color(175, 186, 255));
    }//GEN-LAST:event_pn_laporanMouseExited

    private void pn_pengaturanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_pengaturanMouseEntered
        pn_pengaturan.setBackground(new Color(66, 87, 215));
    }//GEN-LAST:event_pn_pengaturanMouseEntered

    private void pn_pengaturanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_pengaturanMouseExited
        pn_pengaturan.setBackground(new Color(175, 186, 255));
    }//GEN-LAST:event_pn_pengaturanMouseExited

    private void pn_databarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_databarangMouseClicked
        brg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pn_databarangMouseClicked

    private void pn_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_laporanMouseClicked
        report.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pn_laporanMouseClicked

    private void pn_pengaturanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_pengaturanMouseClicked
        setting.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pn_pengaturanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DASHBOARD().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel border;
    private javax.swing.JLabel bt_dashboard;
    private javax.swing.JLabel bt_databarang;
    private javax.swing.JLabel bt_laporan;
    private javax.swing.JLabel bt_pengaturan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel main_layout;
    private javax.swing.JPanel panel_kanan;
    private javax.swing.JPanel panel_welcome;
    private javax.swing.JPanel pn_dashboard;
    private javax.swing.JPanel pn_databarang;
    private javax.swing.JPanel pn_laporan;
    private javax.swing.JPanel pn_pengaturan;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables
}
