/**
 * @author Wijdan Afifi
 */
import javax.swing.*;
public class LOGIN extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LOGIN.class.getName());

    public LOGIN() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sidebar_login = new javax.swing.JPanel();
        Judul = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        usn_login = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        Password = new javax.swing.JLabel();
        pass_login = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        Login = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Register_Now = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Sidebar_login.setBackground(new java.awt.Color(43, 57, 144));
        Sidebar_login.setPreferredSize(new java.awt.Dimension(300, 600));

        Judul.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Judul.setForeground(new java.awt.Color(255, 255, 255));
        Judul.setText("LOGIN");

        Username.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Username");

        usn_login.setBackground(new java.awt.Color(43, 57, 144));
        usn_login.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        usn_login.setForeground(new java.awt.Color(255, 255, 255));
        usn_login.setBorder(null);

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        Password.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");

        pass_login.setBackground(new java.awt.Color(43, 57, 144));
        pass_login.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        pass_login.setForeground(new java.awt.Color(255, 255, 255));
        pass_login.setBorder(null);

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        Login.setBackground(new java.awt.Color(106, 119, 198));
        Login.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("LOGIN");
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.addActionListener(this::LoginActionPerformed);

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Don't Have an account?");

        Register_Now.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Register_Now.setForeground(new java.awt.Color(0, 153, 255));
        Register_Now.setText("Register Now");
        Register_Now.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Register_Now.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Register_NowMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Sidebar_loginLayout = new javax.swing.GroupLayout(Sidebar_login);
        Sidebar_login.setLayout(Sidebar_loginLayout);
        Sidebar_loginLayout.setHorizontalGroup(
            Sidebar_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sidebar_loginLayout.createSequentialGroup()
                .addGroup(Sidebar_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Sidebar_loginLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(Judul))
                    .addGroup(Sidebar_loginLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(Login))
                    .addGroup(Sidebar_loginLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(Sidebar_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(Sidebar_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Username)
                                .addComponent(Password)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(usn_login, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(pass_login)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Register_Now))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        Sidebar_loginLayout.setVerticalGroup(
            Sidebar_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sidebar_loginLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(Judul)
                .addGap(47, 47, 47)
                .addComponent(Username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pass_login, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(Login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Register_Now)
                .addGap(111, 111, 111))
        );

        getContentPane().add(Sidebar_login, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(175, 186, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        String username = usn_login.getText();
        String password = new String(pass_login.getPassword());
        
        boolean log = DATABASE.login(username, password);
        
        if (log){
            DASHBOARD board = new DASHBOARD();
            board.setVisible(true);
            board.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void Register_NowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Register_NowMouseClicked
        REGISTER createAcc = new REGISTER();
        createAcc.setVisible(true);
        createAcc.setLocationRelativeTo(null);
        this.dispose(); 
    }//GEN-LAST:event_Register_NowMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LOGIN().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Judul;
    private javax.swing.JButton Login;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Register_Now;
    private javax.swing.JPanel Sidebar_login;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPasswordField pass_login;
    private javax.swing.JTextField usn_login;
    // End of variables declaration//GEN-END:variables
}
