/**
 * @author Wijdan Afifi
 */
import javax.swing.*;
public class REGISTER extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(REGISTER.class.getName());

    public REGISTER() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Sidebar_regis = new javax.swing.JPanel();
        Judul = new javax.swing.JLabel();
        Nama_lengkap = new javax.swing.JLabel();
        nama_regis = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        Jabatan = new javax.swing.JLabel();
        Admin = new javax.swing.JRadioButton();
        Staff = new javax.swing.JRadioButton();
        Username = new javax.swing.JLabel();
        usn_regis = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        Password = new javax.swing.JLabel();
        pass_regis = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        Daftar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Sidebar_regis.setBackground(new java.awt.Color(43, 57, 144));
        Sidebar_regis.setPreferredSize(new java.awt.Dimension(300, 600));

        Judul.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Judul.setForeground(new java.awt.Color(255, 255, 255));
        Judul.setText("REGISTER");

        Nama_lengkap.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Nama_lengkap.setForeground(new java.awt.Color(255, 255, 255));
        Nama_lengkap.setText("Nama Lengkap");

        nama_regis.setBackground(new java.awt.Color(43, 57, 144));
        nama_regis.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        nama_regis.setForeground(new java.awt.Color(255, 255, 255));
        nama_regis.setBorder(null);

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        Jabatan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Jabatan.setForeground(new java.awt.Color(255, 255, 255));
        Jabatan.setText("Jabatan");

        buttonGroup1.add(Admin);
        Admin.setForeground(new java.awt.Color(255, 255, 255));
        Admin.setText("Admin");

        buttonGroup1.add(Staff);
        Staff.setForeground(new java.awt.Color(255, 255, 255));
        Staff.setText("Staff");

        Username.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Username");

        usn_regis.setBackground(new java.awt.Color(43, 57, 144));
        usn_regis.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        usn_regis.setForeground(new java.awt.Color(255, 255, 255));
        usn_regis.setBorder(null);

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        Password.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");

        pass_regis.setBackground(new java.awt.Color(43, 57, 144));
        pass_regis.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        pass_regis.setForeground(new java.awt.Color(255, 255, 255));
        pass_regis.setBorder(null);

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        Daftar.setBackground(new java.awt.Color(106, 119, 198));
        Daftar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Daftar.setForeground(new java.awt.Color(255, 255, 255));
        Daftar.setText("SIGN UP");
        Daftar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Daftar.addActionListener(this::DaftarActionPerformed);

        javax.swing.GroupLayout Sidebar_regisLayout = new javax.swing.GroupLayout(Sidebar_regis);
        Sidebar_regis.setLayout(Sidebar_regisLayout);
        Sidebar_regisLayout.setHorizontalGroup(
            Sidebar_regisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sidebar_regisLayout.createSequentialGroup()
                .addGroup(Sidebar_regisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Sidebar_regisLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(Sidebar_regisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nama_regis, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Sidebar_regisLayout.createSequentialGroup()
                                .addComponent(Nama_lengkap)
                                .addGap(132, 132, 132))
                            .addGroup(Sidebar_regisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Jabatan)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(Sidebar_regisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Username)
                                    .addComponent(Password)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(usn_regis, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pass_regis)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(Sidebar_regisLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(Admin)
                        .addGap(46, 46, 46)
                        .addComponent(Staff))
                    .addGroup(Sidebar_regisLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(Judul))
                    .addGroup(Sidebar_regisLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(Daftar)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        Sidebar_regisLayout.setVerticalGroup(
            Sidebar_regisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sidebar_regisLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(Judul)
                .addGap(30, 30, 30)
                .addComponent(Nama_lengkap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama_regis, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Jabatan)
                .addGap(7, 7, 7)
                .addGroup(Sidebar_regisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Staff)
                    .addComponent(Admin))
                .addGap(26, 26, 26)
                .addComponent(Username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usn_regis, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pass_regis, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(Daftar)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        getContentPane().add(Sidebar_regis, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(175, 186, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaftarActionPerformed
        String username = usn_regis.getText();
        String password = new String(pass_regis.getPassword());
        String nama_lengkap = nama_regis.getText();
        String jabatan = "";

        if(Admin.isSelected()) {
            jabatan = "Admin Hamada";
        } else if(Staff.isSelected()) {
            jabatan = "Staff";
        } 

        boolean Reg = DATABASE.register(username, password, jabatan, nama_lengkap);
        if (Reg) {
            JOptionPane.showMessageDialog(this, "Registrasi Berhasil!");
            
            this.dispose(); // Menutup Form REGISTER
            
            // Membuka FORM LOGIN
            new LOGIN().setVisible(true); 
            new LOGIN().setLocationRelativeTo(null);                         
        } else {
            JOptionPane.showMessageDialog(this, "Registrasi Gagal! Periksa koneksi database.");
        }
    }//GEN-LAST:event_DaftarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new REGISTER().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Admin;
    private javax.swing.JButton Daftar;
    private javax.swing.JLabel Jabatan;
    private javax.swing.JLabel Judul;
    private javax.swing.JLabel Nama_lengkap;
    private javax.swing.JLabel Password;
    private javax.swing.JPanel Sidebar_regis;
    private javax.swing.JRadioButton Staff;
    private javax.swing.JLabel Username;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField nama_regis;
    private javax.swing.JPasswordField pass_regis;
    private javax.swing.JTextField usn_regis;
    // End of variables declaration//GEN-END:variables
}
